### ISSUE TITLE
Background Skills - picking them doesn’t check how many you pick. 

### ISSUE THREAD

**Issue by StillAdventuring** [Pjort/Traveller-Tools#1]
On the background skills section I was able to select all the skills and submit them.  It should respect the base count and any education modifiers. 

I am liking it so far. Thanks for doing this. Is it okay to submit issues this way ?
thanks john

**Comment by Pjort** [comment]
It is actually a working as intended, I wanted to have it more sandbox style, where you can generate chars with more freedom. 

But you are not the only one mentioning this, so maybe some visual aid would help. Like a count down of how many more is "legal" to select. 

But I don't want to prevent people having more background skills if the ref alows it or it makes sense for the char.
